'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import dynamic from 'next/dynamic';
import SiteLinks from './site-links';
import SectionExplanation from './section-explanation';
import SheetExtraction from './sheet-extraction';
import definition from '@/data/pimlico-overlay-source.json';
import siteExample from '@/data/pimlico-site-example.json';
import {overlayMatrix,applyMatrix,invertMatrix,toPlane} from '@/lib/map-overlay';
import {COLOUR_CLASSES,EXCLUDED,newColours,colourGrid,generateMask,encodeMask,decodeMask,maskRectangles,buildColourArtifact,displayedSections} from '@/lib/map-colours';

const path=ring=>ring.map((p,i)=>`${i?'L':'M'}${p.join(',')}`).join(' ')+'Z';
const polygonPath=g=>(g.type==='Polygon'?[g.coordinates]:g.coordinates).flatMap(p=>p.map(path)).join(' ');
const colour=id=>COLOUR_CLASSES.find(c=>c.id===id)?.colour??'#69776f';
const TECHNIQUES=[
 {id:'overlap',name:'Exact overlap',description:'Only the colour directly beneath each modern building. Gaps stay grey.'},
 {id:'site-aware',name:'Site-aware',description:'Suggested balance: exact overlap, with complete site colours on explicitly linked replacements.'},
 {id:'filled',name:'Fill surfaces',description:'Extend every matched colour to fill the modern object. This also colours uncertain gaps.'},
];
const BuildingPreview=dynamic(()=>import('../review/object-preview'),{ssr:false,loading:()=> <p>Preparing 3D buildings…</p>});
export default function ColourStage({config,index,onChange,onError}){
 const [siteDraft,setSiteDraft]=useState(null),[selectedSectionId,setSelectedSectionId]=useState('');
 const [manual,setManual]=useState(false),[running,setRunning]=useState(false);
 const [image,setImage]=useState(null),[imageError,setImageError]=useState(''),[category,setCategory]=useState('blast'),[tool,setTool]=useState('sample'),[scope,setScope]=useState('area'),[radius,setRadius]=useState(2),[maskOpacity,setMaskOpacity]=useState(.55),[zoom,setZoom]=useState(1),[selectedId,setSelectedId]=useState(''),[preview,setPreview]=useState('sections'),[draftStroke,setDraftStroke]=useState(null),[notice,setNotice]=useState('');
 const sourceSvg=useRef(null),stroke=useRef(null),settings=config.colours;
 const grid=useMemo(()=>{try{return {value:colourGrid(config.selection)};}catch(e){return {error:e.message};}},[config.selection]);
 const stale=settings&&grid.value&&JSON.stringify(settings?.grid)!==JSON.stringify(grid.value);
 useEffect(()=>{if(!settings||stale)setSiteDraft(null);},[settings,stale]);
 useEffect(()=>{let cancelled=false;const img=new Image();img.onload=()=>{if(!cancelled)setImage(img);};img.onerror=()=>{if(!cancelled)setImageError('The source pixels could not load. Colour selection requires the original local sheet.');};img.src=definition.source.url;return()=>{cancelled=true;};},[]);
 const pixels=useMemo(()=>{
  if(!image||!grid.value)return null;const g=grid.value,canvas=document.createElement('canvas');canvas.width=g.width;canvas.height=g.height;
  const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.drawImage(image,g.x,g.y,g.width,g.height,0,0,g.width,g.height);return ctx.getImageData(0,0,g.width,g.height).data;
 },[image,grid]);
 const result=useMemo(()=>{if(!settings||stale||!index)return {};try{return {artifact:buildColourArtifact(config,definition,index)};}catch(e){return {error:e.message};}},[config,index,settings,stale]);
 const inverse=useMemo(()=>invertMatrix(overlayMatrix(config,definition.pivot)),[config.points,config.adjustment,config.model]);
 const buildings=useMemo(()=>result.artifact?.features.map(f=>{
  const polygons=f.geometry.type==='Polygon'?[f.geometry.coordinates]:f.geometry.coordinates;
  const coordinates=polygons.map(p=>p.map(r=>r.map(c=>applyMatrix(inverse,toPlane(c)))));
  return {...f,path:polygonPath({type:'MultiPolygon',coordinates})};
 })??[],[result,inverse]);
 const sectionMode=preview==='sections'||preview==='3d',surfaceMode=settings?.surfaceMode??'site-aware',fillSurfaces=surfaceMode==='filled';
 const technique=TECHNIQUES.find(t=>t.id===surfaceMode);
 const sectionCollection=useMemo(()=>displayedSections(result.artifact,surfaceMode),[result,surfaceMode]);
 function setSurfaceMode(surfaceMode){setSelectedSectionId('');onChange({...settings,surfaceMode},{label:'building colour finish'});}
 const sections=useMemo(()=>sectionCollection?.features.map(f=>{const coordinates=f.geometry.coordinates.map(p=>p.map(r=>r.map(c=>applyMatrix(inverse,toPlane(c)))));return {...f,path:polygonPath({type:'MultiPolygon',coordinates})};})??[],[sectionCollection,inverse]);
 const selectedSection=sections.find(f=>f.id===selectedSectionId&&f.properties.componentId===selectedId);
 const previewObjects=useMemo(()=>sectionMode?sections.map(f=>({...f,color:colour(f.properties.category),stripes:[]})):result.artifact?.features.map(f=>({...f,color:colour(f.properties.display.categories[0]),stripes:f.properties.display.categories.map(colour)}))??[],[result,sections,sectionMode]);
 const previewParents=useMemo(()=>index?.features.filter(f=>previewObjects.some(o=>o.properties.componentId===f.id))??[],[index,previewObjects]);
 const selected=buildings.find(f=>f.id===selectedId),counts=result.artifact?.metadata.counts;
 const activeSite=settings?.sites?.find(s=>s.targets.includes(selectedId));
 const exampleBuilding=buildings.find(f=>f.properties.buildingId===siteExample.buildingId);
 const canTryExample=exampleBuilding&&siteExample.sourceImageSha256===definition.source.sha256&&siteExample.boundary.every(p=>p[0]>=config.selection.x&&p[0]<=config.selection.x+config.selection.width&&p[1]>=config.selection.y&&p[1]<=config.selection.y+config.selection.height);
 const exampleSite=settings?.sites?.find(s=>s.targets.includes(exampleBuilding?.id));
 function tryExample(){
  setSelectedId(exampleBuilding.id);setSelectedSectionId('');
  const sites=exampleSite?settings.sites:[...(settings.sites??[]),{id:crypto.randomUUID(),name:siteExample.name,boundary:siteExample.boundary,targets:[exampleBuilding.id],relationship:siteExample.relationship,note:siteExample.note,review:'draft'}];
  onChange({...settings,sites,surfaceMode:'site-aware'},{label:'replacement site example'});
  if(preview!=='3d')setPreview('sections');
 }
 const siteBoundary=siteDraft?.boundary??activeSite?.boundary;
 function selectBuilding(id){setSelectedSectionId('');setSelectedId(id);if(siteDraft)setSiteDraft({...siteDraft,targets:siteDraft.targets.includes(id)?siteDraft.targets.filter(v=>v!==id):[...siteDraft.targets,id]});}
 function selectSection(id){const section=sections.find(f=>f.id===id);if(!section){selectBuilding(id);return;}selectBuilding(section.properties.componentId);setSelectedSectionId(id);}
 function updateSites(sites,options){try{const next={...settings,sites,reviews:{}};buildColourArtifact({...config,colours:next},definition,index);onChange(next,options);onError('');return true;}catch(e){onError(e.message);return false;}}
 const rects=useMemo(()=>settings?maskRectangles(decodeMask(settings.runs,settings.grid.width*settings.grid.height),settings.grid):new Map(),[settings]);
 const g=config.selection,padding=Math.max(g.width,g.height)*.08,viewBox=[g.x+g.width/2-(g.width+padding*2)/zoom/2,g.y+g.height/2-(g.height+padding*2)/zoom/2,(g.width+padding*2)/zoom,(g.height+padding*2)/zoom].join(' ');
 function commit(next,options={label:'colour edit'}){
  if(!pixels)return;
  try{
   const value={...next,grid:grid.value,fingerprints:index.fingerprints,reviews:{}},labels=generateMask(pixels,value,definition.exclusions);
   value.runs=encodeMask(labels);onChange(value,options);onError('');setNotice('');
  }catch(e){onError(e.message);}
 }
 function pick(e){const p=new DOMPoint(e.clientX,e.clientY).matrixTransform(sourceSvg.current.getScreenCTM().inverse());return [p.x,p.y];}
 function inside(p){return p[0]>=g.x&&p[0]<g.x+g.width&&p[1]>=g.y&&p[1]<g.y+g.height;}
 function down(e){
  if(siteDraft&&e.button===0){const p=pick(e);if(inside(p)&&siteDraft.boundary.length<100)setSiteDraft({...siteDraft,boundary:[...siteDraft.boundary,p]});return;}
  if(!manual||!pixels||stale||!settings||e.button!==0)return;
  const p=pick(e);if(!inside(p))return;
  if(tool==='sample'){
   if((definition.exclusions??[]).some(r=>p[0]>=r.x&&p[0]<r.x+r.width&&p[1]>=r.y&&p[1]<r.y+r.height)){setNotice('That point is in the watermark band. It remains unknown.');return;}
   if(settings.samples.length>=40){onError('Remove a sample before adding another (40 maximum).');return;}
   const i=(Math.floor(p[1])-grid.value.y)*grid.value.width+Math.floor(p[0])-grid.value.x,rgb=Array.from(pixels.slice(i*4,i*4+3));
   commit({...settings,samples:[...settings.samples,{id:crypto.randomUUID(),category,point:p,rgb,scope}]},{label:'colour sample'});if(category!=='destroyed'&&Math.max(...rgb)-Math.min(...rgb)<60&&Math.min(...rgb)>145)setNotice('That sample is close to the paper tone. Check the suggestions, or undo it and pick a stronger patch of colour.');return;
  }
  if(settings.strokes.length>=500){onError('The correction limit is 500 strokes. Undo a stroke before adding more.');return;}
  stroke.current={id:crypto.randomUUID(),label:tool==='erase'?0:tool==='exclude'?EXCLUDED:COLOUR_CLASSES.findIndex(c=>c.id===category)+1,radius,points:[p]};setDraftStroke({...stroke.current});e.currentTarget.setPointerCapture(e.pointerId);
 }
 function move(e){if(!stroke.current)return;const p=pick(e),last=stroke.current.points.at(-1);if(inside(p)&&Math.hypot(p[0]-last[0],p[1]-last[1])>.25&&stroke.current.points.length<2000){stroke.current.points.push(p);setDraftStroke({...stroke.current});}}
 function up(e){if(!stroke.current)return;commit({...settings,strokes:[...settings.strokes,stroke.current]},{label:tool==='erase'?'erase stroke':tool==='exclude'?'unknown-area stroke':'brush stroke'});stroke.current=null;setDraftStroke(null);if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);}
 function review(status,note=selected?.properties.review.note??''){
  if(selected)onChange({...settings,reviews:{...settings.reviews,[selected.id]:{status,note}}},{label:'review note',group:`review-${selected.id}`});
 }
 async function autoColour(){
  if(!pixels||!index||running)return;setRunning(true);setManual(false);
  await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));
  try{const base=settings??newColours(config.selection,index.fingerprints);commit({...base,automatic:{version:1},samples:[],strokes:[],reviews:{}},{label:'automatic colours'});}finally{setRunning(false);}
 }
 function downloadAreas(){const artifact=result.artifact,areas={...artifact.metadata.colourRegions,metadata:{meaning:'Detected historical colour areas, independent of modern buildings; draft source evidence',sourceImageSha256:artifact.metadata.sourceImageSha256}};const url=URL.createObjectURL(new Blob([JSON.stringify(areas,null,2)],{type:'application/geo+json'})),a=document.createElement('a');a.href=url;a.download='pimlico-historical-colour-areas.geojson';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function downloadSections(){const url=URL.createObjectURL(new Blob([JSON.stringify(sectionCollection,null,2)],{type:'application/geo+json'})),a=document.createElement('a');a.href=url;a.download=`pimlico-${surfaceMode}-building-sections.geojson`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function downloadBuildings(){const url=URL.createObjectURL(new Blob([JSON.stringify(result.artifact,null,2)],{type:'application/geo+json'})),a=document.createElement('a');a.href=url;a.download='pimlico-area-coloured-buildings.geojson';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <section className="colour-tool" aria-label="Colour areas workspace">
  <div className="colour-intro"><div><h2>See the colours automatically.</h2><p>One click to try it. Undo any change with the button above or ⌘Z.</p></div><p>{counts?(sectionMode?`${sections.filter(f=>f.properties.category).length} colour matches · ${buildings.length} modern buildings`:`Buildings: ${counts.single} single · ${counts.mixed} mixed · ${counts.unresolved} unresolved`):'Preparing colour workspace…'}</p></div>
  {(imageError||grid.error||result.error)&&<p className="colour-warning" role="alert">{imageError||grid.error||result.error}</p>}
  {stale&&<p className="colour-warning">The selection changed. Existing samples and corrections are retained. <button disabled={!pixels} onClick={()=>commit(settings??newColours(config.selection,index.fingerprints))}>Refresh colour area</button></p>}
  <div className="colour-auto-actions"><button className="sheet-primary" disabled={!pixels||!index||running||!!siteDraft||Boolean(grid.error)} onClick={autoColour}>{running?'Finding colours…':settings?.automatic?'Run auto again':'Auto colour this area'}</button><button disabled={!settings||running||!!siteDraft} aria-expanded={manual} onClick={()=>setManual(!manual)}>{manual?'Hide manual corrections':'Manual corrections'}</button><span>Automatic suggestions · your alignment stays fixed</span></div>
  <ul className="colour-legend" aria-label="Damage colour legend">{COLOUR_CLASSES.map(c=><li key={c.id} title={c.label}><i style={{background:c.colour}}/>{c.name}</li>)}</ul>
  {manual&&!siteDraft&&<><p className="colour-manual-help">Choose a colour below, then click that colour on the paper. Use a brush to correct an area. Undo works for both.</p><div className="colour-palette" aria-label="Historical damage colours">{COLOUR_CLASSES.map(c=><button key={c.id} aria-pressed={category===c.id} title={c.label} onClick={()=>setCategory(c.id)}><i style={{background:c.colour}}/>{c.name}</button>)}</div>
  <div className="colour-toolbar"><div>{[['sample','Pick colour'],['paint','Add brush'],['erase','Erase brush'],['exclude','Mark unknown']].map(([id,title])=><button key={id} aria-pressed={tool===id} onClick={()=>setTool(id)}>{title}</button>)}</div></div></>}
  <div className="colour-view-tools"><div><button aria-label="Zoom colour maps out" onClick={()=>setZoom(z=>Math.max(1,z/1.3))}>−</button><button aria-label="Zoom colour maps in" onClick={()=>setZoom(z=>Math.min(4,z*1.3))}>+</button><button onClick={()=>setZoom(1)}>Fit paper & 2D</button></div></div>
  <div className="colour-stage">
   <figure><figcaption><strong>Paper & suggested regions</strong><span>{siteDraft?'Click site boundary corners':!manual?(settings?.automatic?'Automatic preview · open manual corrections to edit':'Click Auto colour to generate a preview'):tool==='sample'?`Click a ${COLOUR_CLASSES.find(c=>c.id===category).name.toLowerCase()} patch`:tool==='erase'?'Erase mistaken labels':tool==='exclude'?'Mark unreadable evidence':`Paint ${COLOUR_CLASSES.find(c=>c.id===category).name.toLowerCase()}`}</span></figcaption>
    <svg className={manual||siteDraft?'colour-editing':'colour-inspecting'} ref={sourceSvg} viewBox={viewBox} role="img" aria-label="Colour sampling canvas" onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={()=>{stroke.current=null;setDraftStroke(null);}}>
     <defs><clipPath id="colour-source-clip"><rect {...g}/></clipPath><pattern id="colour-excluded" width="4" height="4" patternUnits="userSpaceOnUse" patternTransform="rotate(45)"><rect width="4" height="4" fill="#797975" fillOpacity=".35"/><rect width="1" height="4" fill="#ece9df" fillOpacity=".7"/></pattern></defs>
     <image href={definition.source.url} width="2060" height="1290" clipPath="url(#colour-source-clip)"/>
     <g clipPath="url(#colour-source-clip)">{!stale&&Array.from(rects).map(([label,rows])=><path key={label} d={rows.map(r=>`M${r.x},${r.y}h${r.width}v1h${-r.width}Z`).join(' ')} fill={label===EXCLUDED?'url(#colour-excluded)':COLOUR_CLASSES[label-1].colour} fillOpacity={maskOpacity} pointerEvents="none"/>)}{definition.exclusions?.map((r,i)=><rect key={i} x={r.x} y={r.y} width={r.width} height={r.height} fill="url(#colour-excluded)" pointerEvents="none"/>)}
      {draftStroke&&<polyline points={draftStroke.points.map(p=>p.join(',')).join(' ')} fill="none" stroke={draftStroke.label>6?'#ddd':draftStroke.label===0?'#fff':COLOUR_CLASSES[draftStroke.label-1].colour} strokeWidth={draftStroke.radius*2} strokeLinecap="round" strokeLinejoin="round" opacity=".8" pointerEvents="none"/>}
     </g>{selectedSection&&sectionMode&&<path d={selectedSection.path} fill={colour(selectedSection.properties.category)} fillOpacity=".25" stroke="#fff3b0" strokeWidth="2" vectorEffect="non-scaling-stroke" pointerEvents="none"/>}{siteBoundary?.length>0&&<polyline points={[...siteBoundary,...(siteDraft?[]:[siteBoundary[0]])].map(p=>p.join(',')).join(' ')} fill="none" stroke="#f9db88" strokeWidth="2" strokeDasharray="5 3" vectorEffect="non-scaling-stroke" pointerEvents="none"/>}{selected&&<path d={selected.path} fill="none" stroke="#fff3b0" strokeWidth="2.5" vectorEffect="non-scaling-stroke" pointerEvents="none"/>}<rect {...g} fill="none" stroke="#e5d9a1" strokeWidth="1" vectorEffect="non-scaling-stroke" pointerEvents="none"/>
    </svg>
   </figure><figure><figcaption><strong>{sectionMode?technique.name:preview==='areas'?'Historical areas & modern outlines':preview==='paper'?'Paper & modern outlines':'Whole modern buildings'}</strong><select aria-label="Building preview style" value={preview} onChange={e=>setPreview(e.target.value)}><option value="sections">2D buildings</option><option value="3d">3D buildings</option><option value="areas">Historical areas & outlines</option><option value="colours">Whole buildings & stripes</option><option value="paper">Paper & outlines</option><option value="outlines">Outlines only</option><option value="whole3d">3D whole buildings & stripes</option></select></figcaption>{sectionMode&&<div className="colour-techniques">
    <div className="colour-finish" role="group" aria-label="Building colour technique">{TECHNIQUES.map(t=><button key={t.id} disabled={!settings||!!siteDraft||running} aria-pressed={surfaceMode===t.id} onClick={()=>setSurfaceMode(t.id)}>{t.name}</button>)}</div>
    <p>{technique.description}</p>
    {canTryExample&&<div className="colour-trial-link">{exampleSite?<span>Russell House: {exampleSite.review==='checked'?'checked':'draft'} site link · {surfaceMode==='overlap'?'ignored in exact overlap':'site colours included'}</span>:<><span>I-building black sits mostly outside today’s footprint.</span><button disabled={!!siteDraft||running||!settings?.runs.some(r=>r[2]<=6)} onClick={tryExample}>Preview Russell House site link</button></>}</div>}
   </div>}{preview==='3d'||preview==='whole3d'?<BuildingPreview objects={previewObjects} buildings={previewParents} onSelect={sectionMode?selectSection:selectBuilding} completePartitions={sectionMode} showFit/>:<svg viewBox={viewBox} role="img" aria-label="Building colour preview">
    <defs>{buildings.filter(f=>f.properties.display.categories.length>1).map((f,i)=><pattern key={f.id} id={`building-mix-${i}`} width={f.properties.display.categories.length*3} height="3" patternUnits="userSpaceOnUse" patternTransform="rotate(45)">{f.properties.display.categories.map((id,n)=><rect key={id} x={n*3} width="3" height="3" fill={colour(id)}/>)}</pattern>)}</defs>
    {preview==='paper'&&<image href={definition.source.url} width="2060" height="1290" clipPath="url(#colour-source-clip)" opacity="1"/>}
    {preview==='areas'&&!stale&&<g clipPath="url(#colour-source-clip)" data-historical-regions="true">{Array.from(rects).map(([label,rows])=><path key={label} d={rows.map(r=>`M${r.x},${r.y}h${r.width}v1h${-r.width}Z`).join(' ')} fill={label===EXCLUDED?'url(#colour-excluded)':COLOUR_CLASSES[label-1].colour} pointerEvents="none"/>)}</g>}
    {sectionMode&&sections.map(f=><path key={f.id} data-building-section={f.id} data-section-category={f.properties.category??'unknown'} d={f.path} fill={colour(f.properties.category)} fillRule="evenodd" stroke={selectedSectionId===f.id?'#fff3b0':'none'} strokeWidth="2" vectorEffect="non-scaling-stroke" role="button" tabIndex={0} aria-label={`${f.properties.name}: ${f.properties.category?COLOUR_CLASSES.find(c=>c.id===f.properties.category).name+(f.properties.kind==='inferred-building-fill'?' filled section':' historical overlap'):'unknown remainder'}`} onClick={()=>selectSection(f.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();selectSection(f.id);}}}><title>{f.properties.category?COLOUR_CLASSES.find(c=>c.id===f.properties.category).label:'Unknown — not evidence of no damage'} · {(f.properties.coverage*100).toFixed(1)}% of modern footprint</title></path>)}
    {buildings.map(f=>{const mixedIndex=buildings.filter(v=>v.properties.display.categories.length>1).findIndex(v=>v.id===f.id);return <path key={f.id} data-colour-building={f.id} d={f.path} pointerEvents={sectionMode?'none':undefined} fill={sectionMode||['outlines','areas','paper'].includes(preview)?'transparent':f.properties.display.categories.length>1?`url(#building-mix-${mixedIndex})`:f.properties.display.categories.length?colour(f.properties.display.categories[0]):'#52645b'} fillRule="evenodd" stroke={selectedId===f.id||siteDraft?.targets.includes(f.id)?'#fff3b0':f.properties.display.rebuilt?'#e7bf7a':'#b8c8bc'} strokeDasharray={f.properties.display.rebuilt?'5 2':undefined} strokeWidth={selectedId===f.id?2.5:.8} vectorEffect="non-scaling-stroke" onClick={()=>selectBuilding(f.id)}><title>{f.properties.name} · {f.properties.display.rebuilt?'Rebuilt site · ':''}{f.properties.display.basis} · {f.properties.status}</title></path>;})}
    <rect {...g} fill="none" stroke="#e5d9a1" strokeDasharray="4 3" strokeWidth="1" vectorEffect="non-scaling-stroke" pointerEvents="none"/>
   </svg>}</figure>
  </div>
  <p className="colour-caption" role="status">{!pixels?'Reading original source pixels…':notice||(siteDraft?'Drawing a historical site. Undo corner removes the last point; Cancel boundary leaves your saved links unchanged.':sectionMode?(surfaceMode==='site-aware'?'Grey means unknown, not empty land. Linked replacements use site colours. These colours describe the earlier site; their divisions on today’s building are illustrative.':fillSurfaces?'Clean colour areas fill each matched building. The expanded colours are display estimates; use Exact overlap to compare with the original evidence.':'Colour follows the historical area inside each modern footprint. Grey is unknown. Click a section to see what it means; these are not flat or original wall boundaries.'):preview==='areas'?'Historical colours stay at their mapped locations, including where no modern building exists. Outlines show today’s buildings; click one to compare.':preview==='paper'?'Original paper under modern outlines. Click a building to highlight the same footprint in both views.':settings?.automatic||settings?.samples.length?'Stripes mean mixed colours. Grey means unresolved. Watermark-obscured evidence stays unknown.':'Click Auto colour this area to see a first pass. Clicking the paper does nothing until you open manual corrections.')}</p>
  {selected&&<section className="colour-diagnosis" aria-label="Selected building explanation">
   <div><strong>{selected.properties.name} · {selected.id.slice(-4)}{selected.properties.display.rebuilt?' · Rebuilt site':''}</strong><button onClick={()=>setSelectedId('')} aria-label="Clear building selection">Close</button></div>
   <p>Original map overlap: {(selected.properties.coverage*100).toFixed(1)}% detected colour · {(selected.properties.unclassifiedCoverage*100).toFixed(1)}% unclassified · {(selected.properties.excludedCoverage*100).toFixed(1)}% excluded · {(selected.properties.outsideSelectionCoverage*100).toFixed(1)}% outside selection</p>
   {sectionMode&&<SectionExplanation building={selected} section={selectedSection} filled={selectedSection?selectedSection.properties.kind==='inferred-building-fill':fillSurfaces||(surfaceMode==='site-aware'&&!!selected.properties.display.siteId&&selected.properties.display.rebuilt)}/>}
   {!sectionMode&&<p>{selected.properties.display.siteId?`${selected.properties.display.basis==='reviewed-site'?'Checked':'Draft'} site link: this building shows all detected colours in the linked historical site. The footprint percentages above remain a separate spatial comparison.`:selected.properties.status==='unresolved'?`Whole-building preview stays grey: detected colour covers less than the ${Math.round(settings.rules.minimumCoverage*100)}% minimum.`:selected.properties.status==='mixed'?'Whole-building preview uses stripes because several colours meet the mixed-share rule. The stripe positions do not mark historical boundaries.':`Whole-building preview fills the entire object ${COLOUR_CLASSES.find(c=>c.id===selected.properties.category)?.name.toLowerCase()}, based on its largest detected colour overlap.`}</p>}
   {selected.properties.display.rebuilt&&<p className="colour-warning">Replacement site: today’s footprint can occupy former open space. Overlap measures location, not which historical buildings were destroyed. Keep the historical areas visible when checking this site.</p>}
   {selected.properties.excludedCoverage>.25&&<p>{sectionMode&&fillSurfaces?'Some original evidence is hidden by the watermark. Filled surfaces estimate colour in those gaps.':'Much of this footprint is excluded by the watermark band. Lowering the threshold cannot recover the obscured evidence.'}</p>}
  </section>}
  {(selected||siteDraft)&&settings&&!stale&&<SiteLinks draft={siteDraft} setDraft={setSiteDraft} selected={selected} sites={settings.sites??[]} artifact={result.artifact?.metadata.sites} onSites={updateSites} onPreview={setPreview}/>}
  <details className="colour-fine-tuning"><summary>Details & fine-tuning <span>Optional · samples, coverage rules and review notes</span></summary><div className="colour-controls">
   <section><h3>1. Refine regions</h3><label>Manual sample tolerance <output>{settings?.tolerance}</output><input aria-label="Colour tolerance" type="range" min="5" max="100" step="1" disabled={!pixels||!settings||stale} value={settings?.tolerance??36} onChange={e=>commit({...settings,tolerance:Number(e.target.value)},{label:'sample tolerance',group:'colour-tolerance'})}/></label><label>Sample reach<select aria-label="Sample reach" value={scope} onChange={e=>setScope(e.target.value)}><option value="area">Similar patches across the area</option><option value="patch">Only the connected patch</option></select></label><label>Brush radius · source pixels<input aria-label="Brush radius" type="range" min=".5" max="12" step=".5" value={radius} onChange={e=>setRadius(Number(e.target.value))}/></label><label>Region preview opacity<input aria-label="Region preview opacity" type="range" min="0" max="1" step=".05" value={maskOpacity} onChange={e=>setMaskOpacity(Number(e.target.value))}/></label><details><summary>Small patches & samples ({settings?.samples.length??0})</summary><label>Minimum suggested patch · pixels<input aria-label="Minimum suggested patch" disabled={!settings||stale} type="number" min="1" max="40" value={settings?.minPatch??3} onChange={e=>{if(Number.isInteger(e.target.valueAsNumber)&&e.target.valueAsNumber>=1&&e.target.valueAsNumber<=40)commit({...settings,minPatch:e.target.valueAsNumber});}}/></label>{settings?.samples.map((s,i)=><p className="colour-sample" key={s.id}><i style={{background:`rgb(${s.rgb.join(',')})`}}/>{COLOUR_CLASSES.find(c=>c.id===s.category).name} · {s.scope==='area'?'area':'patch'}<button aria-label={`Remove colour sample ${i+1}`} onClick={()=>commit({...settings,samples:settings.samples.filter(v=>v.id!==s.id)},{label:'remove sample'})}>Remove</button></p>)}</details><p>Black ink and lettering can resemble damage fills. Erase mistaken labels. The watermark band is kept unknown.</p></section>
   <section><h3>2. Set building rules</h3><label>Minimum coloured coverage <output>{Math.round((settings?.rules.minimumCoverage??.35)*100)}%</output><input aria-label="Minimum coloured coverage" type="range" min=".1" max=".9" step=".05" disabled={!settings||stale} value={settings?.rules.minimumCoverage??.35} onChange={e=>onChange({...settings,rules:{...settings.rules,minimumCoverage:Number(e.target.value)},reviews:{}},{label:'coverage rule',group:'coverage'})}/></label><label>Mixed colour share <output>{Math.round((settings?.rules.mixedShare??.2)*100)}%</output><input aria-label="Mixed colour share" type="range" min=".1" max=".45" step=".05" disabled={!settings||stale} value={settings?.rules.mixedShare??.2} onChange={e=>onChange({...settings,rules:{...settings.rules,mixedShare:Number(e.target.value)},reviews:{}},{label:'mixed-colour rule',group:'mixed-share'})}/></label><p>Coverage uses the complete building footprint, including parts outside the selection. A mixed colour needs this share of coloured coverage and at least 5% of the whole footprint.</p><p>These are display rules, not confidence scores. Grey buildings have insufficient colour evidence. 3D heights use source estimates where available.</p><p className="colour-warning">Colours describe the historical area beneath today’s buildings. The I-shaped replacement is a site relationship, not a claim that the current building was bombed.</p><button disabled={!result.artifact} onClick={downloadSections}>Download displayed sections</button><button disabled={!result.artifact} onClick={downloadAreas}>Download historical areas</button><button disabled={!result.artifact} onClick={downloadBuildings}>Download buildings GeoJSON</button></section>
   <section><h3>3. Check examples</h3><label>Inspect building<select aria-label="Inspect coloured building" value={selectedId} onChange={e=>setSelectedId(e.target.value)}><option value="">Click a building or choose here</option>{buildings.map(f=><option key={f.id} value={f.id}>{f.properties.name} · {f.id.slice(-4)} · {f.properties.status}</option>)}</select></label>{selected?<><strong>{selected.properties.name}</strong><p>{selected.properties.status} · {selected.properties.relationship==='rebuilt-site'?'Known replacement site':'Historical identity unverified'}</p><p>{(selected.properties.coverage*100).toFixed(0)}% coloured · {(selected.properties.excludedCoverage*100).toFixed(0)}% excluded · {(selected.properties.outsideSelectionCoverage*100).toFixed(0)}% outside selection</p>{selected.properties.categories.map(p=><p key={p.category}>{COLOUR_CLASSES.find(c=>c.id===p.category).name}: {(p.coverage*100).toFixed(1)}% of footprint</p>)}<label>Visual review<select aria-label="Visual review" value={selected.properties.review.status} onChange={e=>{if(e.target.value==='unreviewed'){const reviews={...settings.reviews};delete reviews[selected.id];onChange({...settings,reviews});}else review(e.target.value);}}><option value="unreviewed">Unreviewed</option><option value="checked">Checked against this paper image</option><option value="needs-correction">Needs correction</option></select></label><label>Review note<textarea value={selected.properties.review.note} maxLength={2000} onChange={e=>review(selected.properties.review.status==='unreviewed'?'needs-correction':selected.properties.review.status,e.target.value)}/></label></>:<p>Inspect clear orange rows, red/orange boundaries, mixed black/purple and replacement sites. Keep unclear examples unresolved.</p>}<p>{result.artifact?.metadata.reviewed??0} checked examples. Changing alignment, colour regions or coverage rules clears these visual checks.</p></section>
  </div></details>
  <SheetExtraction image={image} config={config} definition={definition}/>
 </section>;
}
